# Generated by Django 4.1.3 on 2022-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(max_length=300),
        ),
    ]
